moneymanagerex/android-money-manager-ex

res/values/strings.xml
Hi,
I adjusted the label of "repeating" to "recurring" transactions as that term seems to be more in use when in relation to financial transactions. 
However, the desktop version is using "repeating transactions" so the change should happen there too, for consistency, if this is adopted. Hence I created a separate request (https://github.com/moneymanagerex/moneymanagerex/issues/414).
=> Updating labels: renaming repeating to recurring.

res/menu/menu_payee.xml, src/com/money/manager/ex/AccountListActivity.java, src/com/money/manager/ex/MainActivity.java, src/com/money/manager/ex/PayeeActivity.java
Hi,
Here are some small changes I made for faster use of the application :
- On the account list page : show the context menu with a single tap (before there was no action for single tap);
- On the payee page : use a small menu to change sorting instead of a dialog menu (less click and closer on a big screen like a tablet)
(Only problem, the <a href="https://github.com/moneymanagerex/android-money-manager-ex/issues/75">issue 75</a> is also present on this overflow menu);
- Correcting the donate icon with the material dark theme.
=> Small improvements for faster use of the application

res/layout/webview_activity.xml
There was no toolbar on this page causing the problem when trying to call setDisplayHomeAsUpEnabled on the toolbar.
=> Fixes force close problem in "Help" of dropbox settings

res/values/strings.xml
The "empty recurring transactions" text was missed when instructions were added to replace the default text.
=> updating the 'empty recurring transactions' string with instructions

src/com/money/manager/ex/AccountListEditActivity.java, src/com/money/manager/ex/CurrencyFormatsListActivity.java, src/com/money/manager/ex/MainActivity.java, src/com/money/manager/ex/settings/GeneralSettingsActivity.java, src/com/money/manager/ex/utils/CurrencyUtils.java
The look & behaviour of the Currency list now depends on the action requested.
In Edit mode, there are no selection checkboxes and the context menu is displayed only on long tap.
In Pick mode, there are selection checkboxes and NO context menu on single tap.
Implements #92.
=> Currencies, no context menu

res/values/strings.xml, src/com/money/manager/ex/CheckingAccountActivity.java, src/com/money/manager/ex/RepeatingTransactionActivity.java
I corrected it by adding a dialog warning that the two accounts are identical when trying to save the transaction like suggested by Alessandro (also corrected for repeated transactions).
=> Fixes #110

src/com/money/manager/ex/CheckingAccountActivity.java, src/com/money/manager/ex/recurring/transactions/RepeatingTransactionActivity.java
Updating confirmation actions to match the selection text. This should have been included with #146
=> updating confirmation actions

app/src/main/java/com/money/manager/ex/account/AccountTransactionListFragment.java, app/src/main/java/com/money/manager/ex/settings/LookAndFeelSettings.java, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/prefids.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/look_and_feel_settings.xml
Duplicate of the #880 for the dev branch.
Current sorting is [Date DESC, TransactionType, ID DESC]. If "Shows the balance for each transaction" is enabled, it can create create situation when some transaction have negative balance.
I have added option to have sorting by [Date DESC, ID DESC] that will sort transaction as they were added.
=> Allow to configure transactions sorting.

app/src/main/java/com/money/manager/ex/account/AccountTransactionListFragment.java, app/src/main/java/com/money/manager/ex/common/AllDataListFragment.java, app/src/main/java/com/money/manager/ex/home/HomeFragment.java
Fixed "Show Transaction", "Show the balance for each transaction", "Hide Reconciled Amounts" preferences.
=> Fix #881. Apply transaction-related preferences without the app restart.

app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java
When using MMEX Android, if the recurrence type was set to MONTHLY_LAST_DAY or MONTHLY_LAST_BUSINESS_DAY (15, 16 respectively), the month would not advance.
=> RecurringTransactionService set month to the next month before finding last date (rules 15,16)

app/src/main/java/com/money/manager/ex/settings/LookFeelPreferenceFragment.java, app/src/main/res/xml/preferences_look_and_feel.xml
Also checkboxes are used in the Dropbox preferences view, but I'm not sure that this view is used by application.
=> Use switches instead of checkboxes on the "Look and Feel" preferences view.

app/src/main/AndroidManifest.xml, app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java, app/src/main/java/com/money/manager/ex/budget/BudgetDetailFragment.java, app/src/main/java/com/money/manager/ex/budget/BudgetPeriodEnum.java, app/src/main/java/com/money/manager/ex/budget/BudgetPeriods.java, app/src/main/java/com/money/manager/ex/budget/BudgetsActivity.java, app/src/main/java/com/money/manager/ex/datalayer/BudgetEntryRepository.java, app/src/main/java/com/money/manager/ex/settings/AppSettings.java, app/src/main/java/com/money/manager/ex/settings/BudgetSettings.java, app/src/main/java/com/money/manager/ex/settings/BudgetSettingsActivity.java, app/src/main/java/com/money/manager/ex/settings/BudgetSettingsFragment.java, app/src/main/java/com/money/manager/ex/settings/SettingsFragment.java, app/src/main/res/layout/item_budget_simple.xml, app/src/main/res/layout/item_budget_simple_header.xml, app/src/main/res/values/prefids.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/main/res/xml/preferences_budget.xml
I've been using Money Manager Ex for months now and I have some ideas to improve the budgeting part.
Changes in this PR:
- Added coloring for the values in the "Actual" column in budgets whether they are above/below the planned amount.
- Added a Settings panel for budgets and added a simplified budget view where the frequency is hidden and only the difference of planned and actual amounts are shown. The intention behind this is to reduce the amount of information on this list; hopefully this makes it easier to understand the current status of the cash flow just by glancing on the figures. This is somewhat related to #804.
- Amended BudgetActivity to only use fragment back stack in single panel UI.
Planned changes:
- New setting to open the current budget (if exists) when choosing Budgets …
=> Enhanced budgeting

app/src/main/java/com/money/manager/ex/core/TransactionStatuses.java
It was introduced in desktop MMEx 1.4.x.
=> fix(#1141): Add support for "N" as a code for "NONE" TransactionStatus

app/src/main/java/com/money/manager/ex/about/AboutFragment.java, app/src/main/java/com/money/manager/ex/database/ViewMobileData.java, app/src/main/java/com/money/manager/ex/reports/PayeeReportAdapter.java, app/src/main/java/com/money/manager/ex/reports/PayeeReportFragment.java, app/src/main/java/com/money/manager/ex/search/SearchActivity.java, app/src/main/res/values/privatestrings.xml
Found that the issue with 1225 was also on my phone (and the VM).  Was able to replicate with a new database along with my own (2 years of data).  Issue appears to stem from the constant names - they'll come through the cursor as Payee instead of PAYEE, making an unhandled column index < 0 error come through.
I also threw in here a fix for a nag for me - the copyright screen stated to 2015, made it dynamic.
=> Suggested fix for #1225

app/src/main/java/com/money/manager/ex/database/MmxOpenHelper.java
updated MmxOpenHelper.java to always disable write ahead logging before init or open a db.
I've tested this on a Nexus 7 emulator running Android 4.1.  Runs without crashing, creating and opening and adding records to a database.
I've also tested this on a Google Pixel emulator running Android Pie.  Instead of making the wal/shm files, it  updates the .mmb and syncs it to the remote provider, as configured.
=> Fix Issue 1254, database does not sync or update on android pie - and makes shm/wal files instead

app/build.gradle, app/src/test/java/org/moneymanagerex/android/testhelpers/UnitTestHelper.java, app/src/test/java/org/moneymanagerex/android/tests/AccountServiceTests.java, app/src/test/java/org/moneymanagerex/android/tests/AccountTests.java, app/src/test/java/org/moneymanagerex/android/tests/AssetAllocationTests.java, app/src/test/java/org/moneymanagerex/android/tests/BaseTests.java, app/src/test/java/org/moneymanagerex/android/tests/CurrencyServiceTests.java, app/src/test/java/org/moneymanagerex/android/tests/DataGenerationTests.java, app/src/test/java/org/moneymanagerex/android/tests/DatabaseMetadataFactoryTests.java, app/src/test/java/org/moneymanagerex/android/tests/DefinedDateRangesTests.java, app/src/test/java/org/moneymanagerex/android/tests/EditTransactionTests.java, app/src/test/java/org/moneymanagerex/android/tests/JavaMoneyTests.java, app/src/test/java/org/moneymanagerex/android/tests/MainActivityTests.java, app/src/test/java/org/moneymanagerex/android/tests/MmexApplicationTests.java, app/src/test/java/org/moneymanagerex/android/tests/MmexHelperTests.java, app/src/test/java/org/moneymanagerex/android/tests/MmxDateTimeTests.java, app/src/test/java/org/moneymanagerex/android/tests/MoneyTests.java, app/src/test/java/org/moneymanagerex/android/tests/NumericHelperTest.java, app/src/test/java/org/moneymanagerex/android/tests/RecentDatabaseProviderTests.java, app/src/test/java/org/moneymanagerex/android/tests/SearchActivityTests.java, app/src/test/java/org/moneymanagerex/android/tests/SplitCategoriesActivityTests.java
uses an interim [drop-in](https://github.com/nimbl3/robolectric.shadows-supportv4) for `robolectric:shadows-support-v4` 
(as mentioned in a [comment](https://github.com/robolectric/robolectric/issues/3985#issuecomment-441390867) on the robolectric issue) 
pending androidx support...
or probably, migrating to `FragmentScenario`: see #1321
TODO:  the migration to robolectric 4 might need further work (e.g. to deal with deprecations)
(but hopefully fixes Travis build for now)
=> Try to fix tests (and hopefully Travis build)

app/src/main/java/com/money/manager/ex/PasscodeActivity.java, app/src/main/java/com/money/manager/ex/home/MainActivity.java, app/src/main/java/com/money/manager/ex/passcode/FingerprintHandler.java, app/src/main/res/layout-land/passcode_activity.xml
Fix #1279:  Migrate `FingerprintManager` to androidx namespace `FingerprintManagerCompat`
Fix #1293:  Don't accidentally bypass passcode e.g. when pressing hardware 'back' button
TODO:
- actually test if fingerprint works after moving to `FingerprintManagerCompat`:  right now the code compiles and (seemingly) runs without problems.  Actual test would need Android 6.0+ with a fingerprint sensor.
- use the new `BiometricPrompt` API (introduced since Android P).   There's a [handy article](https://proandroiddev.com/5-steps-to-implement-biometric-authentication-in-android-dbeb825aeee8?gi=386855d763ca) on the new api (and falling back to `FingerprintManagerCompat` for older versions);    the author has even made [a library](https://github.com/anitaa1990/Biometric-Auth-Sample) bridging the two …
=> Fix Passcode crash after androidx upgrade

app/src/main/res/layout/activity_asset_allocation_overview.xml, app/src/main/res/layout/activity_budget_edit.xml, app/src/main/res/layout/activity_price_edit.xml
Full credits to @funrider1 and @MisterY for the observations and pointers, a big thank you.
Fixes #1326
=> Fix #1326:  Asset Allocation crashes on open, following androidx upgrade

app/build.gradle, app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java, app/src/main/java/com/money/manager/ex/database/ISplitTransaction.java, app/src/main/java/com/money/manager/ex/datalayer/SplitCategoriesRepository.java, app/src/main/java/com/money/manager/ex/domainmodel/SplitCategory.java, app/src/main/java/com/money/manager/ex/domainmodel/SplitRecurringCategory.java, app/src/main/java/com/money/manager/ex/home/SelectDatabaseActivity.java, app/src/main/java/com/money/manager/ex/servicelayer/CategoryService.java, app/src/main/java/com/money/manager/ex/servicelayer/qif/QifRecord.java, app/src/main/java/com/money/manager/ex/settings/DatabaseSettingsFragment.java, app/src/main/java/com/money/manager/ex/transactions/SplitCategoriesActivity.java, app/src/main/java/com/money/manager/ex/transactions/SplitCategoriesAdapter.java
=> continue single category adoption and fallback to current database if download failed

app/src/main/java/com/money/manager/ex/database/QueryAllData.java, app/src/main/java/com/money/manager/ex/notifications/RecurringTransactionNotifications.java
Change Splitted column name to SPLITTED in java/com/money/manager/ex/viewmodels/AccountTransactionDisplay.java
see analisys in #1518
=> Issue #1518 and #1519

app/src/main/java/com/money/manager/ex/home/MainActivity.java, app/src/main/java/com/money/manager/ex/notifications/RecurringTransactionNotifications.java, app/src/main/java/com/money/manager/ex/notifications/SyncNotificationModel.java, app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionListActivity.java, app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionListFragment.java, app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java, app/src/main/res/values/strings.xml, docs/usermanual/index.md
Improvement:
- move automatic creation of recurring transaction from MainActivity to RecurringTransactionNotification
- Setup Multiple Notification (one for every Transaction) with contextual Action (Enter or Skip) and press action (Show Recurring Transaction)
- If RecurringTransaction is Auto and AutomaticExecution is **on**, the schedule transaction is immediately executed. Notification has no action
- If RecurringTransaction is Auto and AutomaticExecution is **off**, the schedule transaction is **not** immediately executed. Notification has action to Skip or Enter transaction
- If RecurringTransaction is Prompt or Manual the schedule transaction is **not** immediately executed. Notification has action to Skip or Enter transaction
From a strictly point of view If mode is Manual, there …
=> Notification Management & Recurring Transaction

app/src/main/java/com/money/manager/ex/account/AccountTransactionListFragment.java, app/src/main/java/com/money/manager/ex/account/AccountTransactionsListViewHolder.java, app/src/main/res/layout-land/merge_header_fragment_account.xml, app/src/main/res/layout-sw600dp-land/merge_header_fragment_account.xml, app/src/main/res/layout/merge_header_fragment_account.xml
The reconcilied amount was shown in AccountTransactionList even when set to Hide in the settings.
This Commit fixes this gap.
Tested on my smartphone only.
As the current master branch does not work (cannot create account or open database), I tested this commit on the last release tag.
=> Hide the reconcilied amount also in the AccountTransactionList

app/src/main/java/com/money/manager/ex/core/RecurringTransactionBootReceiver.java, app/src/main/java/com/money/manager/ex/home/MainActivity.java, app/src/main/java/com/money/manager/ex/notifications/RecurringTransactionProcess.java, app/src/main/java/com/money/manager/ex/notifications/RecurringTransactionReceiver.java, app/src/main/java/com/money/manager/ex/notifications/ScheduledTransactionWorker.java, app/src/main/java/com/money/manager/ex/settings/BehaviourSettings.java, app/src/main/java/com/money/manager/ex/settings/BehaviourSettingsFragment.java, app/src/main/java/com/money/manager/ex/settings/PreferenceConstants.java, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-sl/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/prefids.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_behaviour.xml, docs/usermanual/index.md
Single Switch as "Process Schedule Transaction" that:
- Autopost "Auto" expired Transaction
- Prompt "Prompt" exipred Transaction
- Nothing for "Manual" exipred Transaction
Documentation also updated
Close #1812
Clarification on #1683
Close #1798
refer also to old implementation on PR #1814
=> Refactor for Notification & Autopost switch

metadata/android/en-US/changelogs/1039.txt
the size is fine (maximum size: 500 characters)
```
$ wc -c metadata/android/en-US/changelogs/1039.txt
493 metadata/android/en-US/changelogs/1039.txt
```
https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/
=> change log for v1039 release

MMEX_Icon_Font/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/res/values/strings.xml, money/build.gradle
=> more clear hint when enter password for encrypted database file

app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java, app/src/main/java/com/money/manager/ex/sync/SyncManager.java, app/src/main/java/com/money/manager/ex/sync/SyncPreferenceFragment.java, app/src/main/java/com/money/manager/ex/sync/SyncService.java
=> extra confirm to force push/pull

app/src/main/java/com/money/manager/ex/sync/SyncManager.java, app/src/main/java/com/money/manager/ex/sync/SyncService.java
refine the sync issue mentiond in #1827
=> skip networking check for Phone storage as remote

app/build.gradle, app/src/main/AndroidManifest.xml
change permission for android 13
=> Android 13+

app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java, app/src/main/java/com/money/manager/ex/sync/SyncManager.java
close #1900
This handle request from NextCloud to not read file in main Thread. 
Tested with NextCloud, GDrive and OneDrive
=> Handle NetworkOnMainThreadException for NextCloud Client

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java, app/src/main/java/com/money/manager/ex/budget/BudgetEditActivity.java, app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java, app/src/main/java/com/money/manager/ex/common/CategoryListActivity.java, app/src/main/java/com/money/manager/ex/datalayer/BudgetEntryRepository.java, app/src/main/java/com/money/manager/ex/home/MainActivity.java, app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java
Step 2 for remove unused code #1792
=> Clean code for nestedcategory

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java, app/src/main/java/com/money/manager/ex/utils/MmxDateTimeUtils.java
See dump on gPlay
```
Caused by java.lang.IllegalArgumentException:
at java.text.SimpleDateFormat.compile (SimpleDateFormat.java:953)
at java.text.SimpleDateFormat.initialize (SimpleDateFormat.java:739)
at java.text.SimpleDateFormat.<init> (SimpleDateFormat.java:710)
at com.money.manager.ex.utils.MmxDateTimeUtils.getFormatterFor (MmxDateTimeUtils.java:222)
at com.money.manager.ex.utils.MmxDateTimeUtils.format (MmxDateTimeUtils.java:68)
at com.money.manager.ex.transactions.EditTransactionCommonFunctions.showDate (EditTransactionCommonFunctions.java:1506)
at com.money.manager.ex.transactions.EditTransactionCommonFunctions.initDateSelector (EditTransactionCommonFunctions.java:483)
at com.money.manager.ex.transactions.CheckingTransactionEditActivity.initializeInputControls …
```
=> handle error on date user format

app/src/main/AndroidManifest.xml, app/src/main/java/com/money/manager/ex/common/BaseListFragment.java, app/src/main/java/com/money/manager/ex/common/MmxBaseFragmentActivity.java, app/src/main/java/com/money/manager/ex/core/RequestCodes.java, app/src/main/java/com/money/manager/ex/domainmodel/EntityBase.java, app/src/main/java/com/money/manager/ex/search/SearchParameters.java, app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java, app/src/main/java/com/money/manager/ex/search/SearchParametersViewHolder.java, app/src/main/java/com/money/manager/ex/tag/TagActivity.java, app/src/main/java/com/money/manager/ex/tag/TagListFragment.java, app/src/main/res/layout/search_parameters_fragment.xml
Add Tag in search transaction, so user can filter transaction with specific tag
=> Add Tag in SearchTransaction

app/src/main/java/com/money/manager/ex/passcode/PasscodeActivity.java
=> handle java.lang.RuntimeException on fingerprint

app/src/main/java/com/money/manager/ex/core/docstorage/DocFileMetadata.java, app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java
align with the existing logic to trigger `pollNewRemoteTimestamp`
```
if (remote.lastModified.toDate().before(localLastModified)) {
// The metadata has not been updated yet!
// Solve this problem by polling until new value fetched. (doh!)
pollNewRemoteTimestamp(metadata);
} else {
metadata.remoteLastChangedDate = remote.lastModified.toIsoString();
}
```
=> Sync: forceMetadataRefresh

app/src/main/java/com/money/manager/ex/domainmodel/Category.java, app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
=> Fix nested loadCategoryName ARN

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
Add code with some refinement (but not hope that this solve issue) and improve log, so we can ask to some one that get error to share logcat
=> Refactor: refine while loop limit handling

app/src/main/java/com/money/manager/ex/core/Core.java, app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java, app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
=> Last Used Payee: enable two tiers: account level or global level

app/src/main/java/com/money/manager/ex/database/MmxOpenHelper.java
to impl
- #2219
as there is no schema change from v19 to v20, this is to keep a good compatibility 
it will perform a downgrade from v20 to v19, and expect the new app (either desktop or android) to upgrade from v19 to v20 again.
and in the future release, will update DATABASE_VERSION to 20 and tune the code again
=> Database Version: auto downgrade from v20 to v19 with no schema change

app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java, app/src/main/java/com/money/manager/ex/payee/PayeeListFragment.java
close #2217
@guanlisheng did you have any suggestion to prevent wrong behavior describe in comment https://github.com/moneymanagerex/android-money-manager-ex/issues/2217#issuecomment-2641782515
anyway this code work, even if normaly loader is called twice (excep when reenter in payee fragment after new payee from traneaction)
=> Try to handle correct load of fragment

app/src/main/AndroidManifest.xml, app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java
Updated with additional RegEx to support more transactional sms. Changes are made in the following methods,
- extractTransRefNo
- extractTransPayee
- extractTransRefNo
Also migrated query to support db version 19.
Release Notes: 
1. Handled additional transactional SMS to support creating automatic transaction
2. Now SMS Transaction processing is supported for db version 19
=> Support creating automatic transaction from SMS for database v19

app/src/main/AndroidManifest.xml, app/src/main/java/com/money/manager/ex/home/MainActivity.java, app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java, app/src/main/java/com/money/manager/ex/reports/GeneralReportActivity.java, app/src/main/java/com/money/manager/ex/reports/GeneralReportArrayAdapter.java, app/src/main/java/com/money/manager/ex/reports/GeneralReportFragment.java, app/src/main/res/layout/dialog_general_report.xml, app/src/main/res/layout/fragment_general_report.xml, app/src/main/res/menu-v14/menu_main.xml, app/src/main/res/menu/menu_main.xml, app/src/main/res/values-en-rUS/strings.xml, app/src/main/res/values/strings.xml
General Reports to AMMEX #2138
=> Support for General Reports in AMMEX #2138

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java, app/src/main/res/values-en-rUS/strings.xml, app/src/main/res/values/strings.xml
Included more info in the notification when SMS Receiver fails to create txn automatically. This will help the user to identify what is missing and add the required information to the App. May be Bank A/C no. not mapped or identified payee may not exist.
@wolfsolver , @guanlisheng , I have completed most of the testing for SMS Receiver. Please plan to include it in the next official release.
=> Included more info in the notification when SMS Receiver fails to create txn automatically

app/src/main/java/com/money/manager/ex/tag/TagListFragment.java
Added a trim before checking for space to be replaced by _, so that we can avoid underscore prefixed or suffixed in tag name
=> Added a trim before checking for space to be replaced by _ in Tag Name

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java
Moved OTP skipping logic to top of the section so that we do not need to run thru some of the methods if msg contains OTP.
=> Moved OTP skipping logic to top of the section

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java
SMS Receiver processes the SMS If the SMS sender is like "AT-620012". So I removed ? in the regex to validate correctly.
=> SMS: minor correction in method isTransactionSms

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
Added condition to check if transaction number is populated already when saving txn, if empty then it will be populated automatically else will be left as it is. In this way, whatever is set by SMS receiver will be retained
=> Fix: replace the Transaction Number once SMS Receiver sets the correct transaction number from SMS

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java
Reversed the Initial value isTransactionSms and changed the RegEx pattern to find the number in place of the string. Because some sms shows the sender as "AT-<Name>" or, in Some cases it will be a bank name without using a hyphen.
=> Fixed SMS Receiver processing if SMS sender name doesn't have hyphen

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java, app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java, metadata/android/en-US/changelogs/1074.txt
Fixed SMS Receiver processing if the SMS sender name doesn't have the hyphen (Original PR#2359)
Fixed: Don't replace the Transaction Number once the SMS Receiver sets the correct transaction number from SMS (Original PR#2358)
=> Moving SMS Receiver related bug fixes to 5.1.2 release

app/src/main/java/com/money/manager/ex/settings/SecuritySettings.java, app/src/main/res/xml/preferences_security.xml, metadata/android/en-US/changelogs/1075.txt
Enable Fingerprint Authentication by default, so existing users won't be affected.
Fix for https://github.com/moneymanagerex/android-money-manager-ex/issues/2355
=> 5.1.3 : Enable Fingerprint Authentication by default (ISSUE #2355)

app/src/main/java/com/money/manager/ex/home/MainActivity.java, app/src/main/res/values/strings.xml
v5.1 : Added fix to clear the passcode set as "FingerprintAuthenticationSuccess". Following msg will to shown in this case and passcode will be removed automatically.
Issue: #2381
=> v5.1 : Added fix to clear the passcode set as "FingerprintAuthenticationSuccess"

app/src/main/java/com/money/manager/ex/reports/IncomeVsExpensesListFragment.java
SparseBooleanArray always keeps the ASC order even though we specify it correctly in the selection query. I have added a fix to address this issue.
@wolfsolver , please check if this has an impact in any other places.
=> Changed the Year Selection Sort Order to DESC (Current year in TOP ) in Income Vs Expense report

docs/CNAME
website work under: https://moneymanagerex.org/android-money-manager-ex/
cname will permit to work as https://android.moneymanagerex.org
see: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#cname-errors
=> Missing CNAME file
