moneymanagerex/android-money-manager-ex

src/com/money/manager/ex/RepeatingTransactionListActivity.java

Hi,
I implemented the one-tap menu display, in relation to #42.
Would you mind providing some feedback on the code and/or accepting the pull request?
Ciao

42 menu on tap

---

res/values/strings.xml

Minor grammar corrections

---

res/layout-land/input_amount_dialog.xml
res/layout/input_amount_dialog.xml
res/values-land/dimens.xml
res/values/dimens.xml
res/values/styles.xml

Fix input amount dialog in landscape orientation

Fix input amount dialog in landscape orientation

---

src/com/money/manager/ex/fragment/HomeFragment.java

Closed #55

---

src/com/money/manager/ex/CurrencyFormatsListActivity.java

Showing currency context menu on single tap.

---

res/values/strings.xml
src/com/money/manager/ex/RepeatingTransactionListActivity.java
src/com/money/manager/ex/adapter/AllDataAdapter.java

Implementation of #78.
Also includes full implementation for #41.

Split indicator on list of transactions

---

src/com/money/manager/ex/view/RobotoCheckBox.java

Partial implementation of #95.

Fixing the split checkbox overlap on jelly bean.

---

res/values/strings.xml
src/com/money/manager/ex/AccountListEditActivity.java
src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/RepeatingTransactionActivity.java
src/com/money/manager/ex/SplitTransactionsActivity.java
src/com/money/manager/ex/fragment/AllDataFragment.java
src/com/money/manager/ex/fragment/SplitItemFragment.java
src/com/money/manager/ex/preferences/TimePreference.java
src/com/money/manager/ex/tutorial/TutorialGlobalFragment.java
src/com/money/manager/ex/tutorial/TutorialTransactionsFragment.java

Split transaction sum & display

---

src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/fragment/AllDataFragment.java

deleting related splits when deleting a transaction

---

build.gradle
res/layout/checkingaccount_activity.xml
res/layout/item_splittransaction.xml
res/layout/splittransaction_activity.xml
res/raw/credits_thirdparty.html
res/values/attrs.xml
res/values/themes.xml
src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/MainActivity.java
src/com/money/manager/ex/SplitTransactionsActivity.java
src/com/money/manager/ex/core/Core.java
src/com/money/manager/ex/fragment/SplitItemFragment.java
src/com/money/manager/ex/recurring/transactions/RepeatingTransactionListFragment.java
src/com/money/manager/ex/settings/LookFeelFragment.java
src/com/money/manager/ex/settings/LookFeelSettingsActivity.java

Styling fixes for #125, #95, & #79.

Black split checkbox

---

res/layout/item_generic_report_2_columns.xml
res/layout/tablerow_income_vs_expenses.xml

I added a few margin to the tables of all the reports. I think it is easier to read (and a little more beautiful) this way. Let me know if it's OK.

Add margin to the tables in the report section for easier readability

---

src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/recurring/transactions/RepeatingTransactionActivity.java

Disable amount on split

---

build.gradle
res/layout/abs_list_fragment.xml
res/layout/base_toolbar_activity.xml
src/com/money/manager/ex/PayeeActivity.java
src/com/money/manager/ex/core/AbsListFragment.java
src/com/money/manager/ex/fragment/BaseListFragment.java
src/com/money/manager/ex/fragment/PayeeLoaderListFragment.java

'Add' button visible on search

---

res/values/arrays.xml
src/com/money/manager/ex/CurrencyFormatsListActivity.java
src/com/money/manager/ex/fragment/CurrencyFormatsLoaderListFragment.java

option for updating a single currency

---

res/layout/checkingaccount_activity.xml

Moving Transaction Type to the top of the entry form

---

src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/recurring/transactions/RepeatingTransactionActivity.java

Implementation of #145 
Correcting the order of confirmation options on a dialog.

Confirmation order

---

res/layout/repeatingtransaction_activity.xml
src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/recurring/transactions/RepeatingTransactionActivity.java

New split checkbox on recurring transaction

---

res/layout/checkingaccount_activity.xml
res/layout/repeatingtransaction_activity.xml

Date on top

---

src/com/money/manager/ex/fragment/HomeFragment.java

Fixing the icon for checking accounts when scrolling back into view.

---

src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/fragment/SplitItemFragment.java
src/com/money/manager/ex/recurring/transactions/RepeatingTransactionActivity.java

Disable split on transfers

---

src/com/money/manager/ex/reports/CategoriesReportActivity.java

removing extra comments in the SQL statement

---

res/layout/repeatingtransaction_activity.xml

moving transaction type above account for recurring transactions

---

res/raw/changelog.xml
res/raw/query_account_bills.sql
res/values/strings.xml
src/com/money/manager/ex/Constants.java
src/com/money/manager/ex/fragment/HomeFragment.java

Implementation of #82.
Only showing investment account list with balances on dashboard.

Show investment accounts on dashboard

---

res/layout/splittransaction_activity.xml
src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/SplitTransactionsActivity.java

removing dead code and formatting comments

Minor cleanup while debugging

---

res/layout/item_account_bills.xml
res/layout/widget_item_account_bills.xml
res/values/prefids.xml
res/values/strings.xml
res/xml/look_and_feel_settings.xml
res/xml/settings.xml
src/com/money/manager/ex/fragment/HomeFragment.java
src/com/money/manager/ex/settings/AppSettings.java
src/com/money/manager/ex/settings/LookFeelFragment.java
src/com/money/manager/ex/settings/PreferencesConstant.java
src/com/money/manager/ex/widget/AccountBillsWidgetService.java

Hide reconciled amounts dashboard

---

res/layout-land/input_amount_dialog.xml
res/layout/input_amount_dialog.xml
src/com/money/manager/ex/fragment/InputAmountDialog.java

adding clear button on amount entry (calculator)

---

src/com/money/manager/ex/businessobjects/RecurringTransaction.java
src/com/money/manager/ex/recurring/transactions/RepeatingTransactionListFragment.java
src/com/money/manager/ex/utils/DateUtils.java

deleting once-occurring transaction on skip

---

res/values/strings.xml
src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/SplitTransactionsActivity.java
src/com/money/manager/ex/checkingaccount/YesNoDialog.java
src/com/money/manager/ex/checkingaccount/YesNoDialogListener.java

Implementation for #175 and #189

Handle transition to Transfer transaction type when there are Split Categories

---

src/com/money/manager/ex/AccountListEditActivity.java
src/com/money/manager/ex/adapter/AllDataAdapter.java

Closing cursors; minor corrections as suggested by code analysis.

Studio suggestions

---

src/com/money/manager/ex/CheckingAccountActivity.java

fix crash on create new transaction

checking if there are any split transactions before using them

---

src/com/money/manager/ex/utils/DateUtils.java

Use the first date format if none are selected

Fixes #230

---

src/com/money/manager/ex/dropbox/DropboxHelper.java

fix for the exception reported in the Android developer console
java.lang.NullPointerException

checking for null exception message to prevent further exceptions

---

README.md
src/com/money/manager/ex/fragment/AllDataFragment.java
src/com/money/manager/ex/search/SearchActivity.java
src/com/money/manager/ex/search/SearchFragment.java

Search result actions toolbar

---

README.md
src/com/money/manager/ex/adapter/AllDataAdapter.java
src/com/money/manager/ex/fragment/AllDataFragment.java
src/com/money/manager/ex/search/SearchActivity.java
src/com/money/manager/ex/search/SearchFragment.java

Fixes #237 & #217 
Includes all the changes in #239 pull request.

Search results group titles

---

src/com/money/manager/ex/database/QueryAllData.java
src/com/money/manager/ex/database/ViewMobileData.java
src/com/money/manager/ex/fragment/AllDataFragment.java
src/com/money/manager/ex/search/SearchFragment.java

Correcting the comparison operators for the amount >= & <=.

---

src/com/money/manager/ex/fragment/AllDataFragment.java
src/com/money/manager/ex/search/SearchActivity.java
src/com/money/manager/ex/search/SearchFragment.java

Group titles rotation

---

build.gradle
res/values/prefids.xml
res/values/strings.xml
res/xml/database_settings.xml
src/com/money/manager/ex/MainActivity.java
src/com/money/manager/ex/MoneyManagerApplication.java
src/com/money/manager/ex/database/DatabaseMigrator14To20.java
src/com/money/manager/ex/settings/AppSettings.java
src/com/money/manager/ex/settings/DatabaseFragment.java
src/com/money/manager/ex/settings/DatabaseSettings.java
src/com/money/manager/ex/settings/DatabaseSettingsActivity.java

migration of existing databases from the old location to the new

---

res/menu/menu_watchlist.xml
res/values/strings.xml
src/com/money/manager/ex/businessobjects/qif/QifExport.java
src/com/money/manager/ex/core/file/TextFileExport.java
src/com/money/manager/ex/investment/PriceCsvExport.java
src/com/money/manager/ex/investment/WatchlistFragment.java

Exporting current security prices to CSV.
#262

Csv price export

---

src/com/money/manager/ex/CheckingAccountActivity.java

Making the Payee an optional input
#278

making Payee optional

---

res/layout-land/merge_header_fragment_account.xml
res/layout/merge_header_fragment_account.xml
src/com/money/manager/ex/fragment/AllDataFragment.java

Balance wrapping fix

---

res/layout-land/input_amount_dialog.xml
res/layout/input_amount_dialog.xml

Adding a scrollbar in amount input dialog on small screens.

---

res/values/prefids.xml
res/values/strings.xml
res/xml/database_settings.xml
src/com/money/manager/ex/database/MmexDatabase.java
src/com/money/manager/ex/settings/DatabaseFragment.java

database integrity check

---

res/values/strings.xml
src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/SplitTransactionsActivity.java
src/com/money/manager/ex/core/Core.java
src/com/money/manager/ex/fragment/SplitItemFragment.java
src/com/money/manager/ex/interfaces/ISplitTransactionsDataset.java

Fix for #309.
Negative total is not allowed on Split Categories screen.

Negative split amounts

---

src/com/money/manager/ex/MoneyManagerProvider.java
src/com/money/manager/ex/database/Dataset.java
src/com/money/manager/ex/database/TableSplitTransactions.java
src/com/money/manager/ex/fragment/AllDataFragment.java
src/com/money/manager/ex/search/ParameterizedWhereClause.java
src/com/money/manager/ex/search/SearchFragment.java

Search category in splits

---

res/values/prefids.xml
res/values/strings.xml
res/xml/general_settings.xml
src/com/money/manager/ex/CheckingAccountActivity.java
src/com/money/manager/ex/database/AccountRepository.java
src/com/money/manager/ex/search/SearchFragment.java
src/com/money/manager/ex/settings/AppSettings.java
src/com/money/manager/ex/settings/GeneralSettings.java
src/com/money/manager/ex/settings/GeneralSettingsFragment.java
src/com/money/manager/ex/settings/PreferenceConstants.java

Remember last used account

---

app/src/main/res/layout/activity_edit_account.xml
app/src/main/res/layout/activity_edit_checking_account_transaction.xml
app/src/main/res/layout/activity_edit_recurring_transaction.xml

UI fixes for FontIcon buttons on the Edit Transaction and Edit Account views.

---

app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionViewHolder.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionViewHolder.java
app/src/main/res/layout/activity_edit_checking_account_transaction.xml
app/src/main/res/layout/activity_edit_recurring_transaction.xml

Added buttons to increase/decrease date without date picker opening. Affected views: Edit Transaction and Edit Recurring Transaction. 
Investment Edit is not using date from the UI at all.

Add date adjustment buttons to quick set previous/next day.

---

app/src/main/java/com/money/manager/ex/adapter/CategoryExpandableListAdapter.java
app/src/main/java/com/money/manager/ex/common/CategoryListFragment.java
app/src/main/res/layout/simple_expandable_list_item_selector.xml

If Category have no children, click to the Category will select it instead of subcategories folding/unfolding.

Fast Category select

---

app/src/main/res/layout/fragment_filter_dialog.xml

Minor fix for languages with long words. See screenshots.

Fix buttons layout on the Account info dialog

---

app/src/main/java/com/money/manager/ex/servicelayer/AccountService.java
app/src/main/res/layout/item_account_bills.xml

This update makes the loan and shares accounts available in the spinner.
This also makes them available for transactions.
#1170

Show loan and shares accounts in spinner and make them available for transactions.

---

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java

I was not closing the cursor after the db read. Now this is handled.

Minor Correction in the Cursor

---

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java

Correction in the Bank trans RegExp

---

app/src/main/java/com/money/manager/ex/settings/SyncPreferences.java

Just a small fix to get sync working on Xiaomi devices.
For details please see: [Natively bundled dependencies override app dependencies](http://en.miui.com/thread-478639-1-1.html)

address #1204

---

app/src/main/java/com/money/manager/ex/datalayer/SubcategoryRepository.java
app/src/main/java/com/money/manager/ex/domainmodel/Subcategory.java
app/src/main/java/com/money/manager/ex/servicelayer/CategoryService.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/transactions/IntentDataParameters.java

Enhance integration with Tasker. Allow saving transaction data without additional interaction.

Extended external intent data with additional parameters

---

app/src/main/java/com/money/manager/ex/database/ViewMobileData.java
app/src/main/java/com/money/manager/ex/home/DashboardFragment.java
app/src/main/java/com/money/manager/ex/reports/PayeeReportFragment.java

Fix chart generation for Payee Report. Related to #1225.

---

MMEX_Icon_Font/build.gradle
app/build.gradle
app/proguard-rules.pro
app/src/main/java/com/money/manager/ex/account/AccountListFragment.java
app/src/main/java/com/money/manager/ex/account/FilterDialogFragment.java
app/src/main/java/com/money/manager/ex/assetallocation/AssetAllocationContentsFragment.java
app/src/main/java/com/money/manager/ex/assetallocation/AssetClassEditFragment.java
app/src/main/java/com/money/manager/ex/currency/CurrencyUIFeatures.java
app/src/main/java/com/money/manager/ex/investment/InvestmentTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/investment/watchlist/WatchlistFragment.java
app/src/main/java/com/money/manager/ex/investment/watchlist/WatchlistItemsFragment.java
app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionListFragment.java
app/src/main/res/raw/credits_thirdparty.html

... housekeeping dependency updates;  updated FontAwesome 4 to 5 as a result.

Update Android Iconics and Timber

---

app/build.gradle
app/src/main/java/com/money/manager/ex/reports/IncomeVsExpensesChartFragment.java
app/src/main/java/com/money/manager/ex/reports/PieChartFragment.java

and deal with some breaking api changes in migration to MPAndroidChart 3

Upgrade MPAndroidChart to 3.1.0

---

.gitignore
MMEX_Icon_Font/build.gradle
androidSVG/build.gradle
app/build.gradle
app/src/main/res/layout/activity_asset_allocation_overview.xml
app/src/main/res/layout/activity_budget_edit.xml
app/src/main/res/layout/activity_price_edit.xml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
money/build.gradle

make it work on latest android studio
- upgrade gradle
- updea dependencies
- migrate project to androidX throguh android studio too
- update target sdk version
- temporarly rename app id to `.mmss.fork`, look forwar to change it back to merge back to upstream
---
Hi MMEX team, @vomikan 
I would like to take responsibility to keep mmex-android alive, because I am a very old user.
please le me know your thoughts, or I will probably clone one maintain the fork.
Regards

Make MMEX Android Alive Again! make it work on latest android studio and update dependency and target sdk

---

MMEX_Icon_Font/build.gradle
androidSVG/build.gradle
app/build.gradle
app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/res/layout/activity_edit_checking_account_transaction.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
money/build.gradle

Update to SMS Receiver, Gradle and Txn Number

---

app/src/main/java/com/money/manager/ex/core/Core.java
app/src/main/java/com/money/manager/ex/core/RequestCodes.java
app/src/main/java/com/money/manager/ex/settings/DatabaseSettingsActivity.java
app/src/main/java/com/money/manager/ex/settings/DatabaseSettingsFragment.java
app/src/main/res/xml/preferences_database.xml

this is also a workaround to force update remote/external database files to mitigate #1476

support export database to external storage via SAF

---

app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java

search refinement: amount range

---

app/build.gradle
app/src/androidTest/java/org/moneymanagerex/android/testhelpers/UiTestHelpersEspresso.java
app/src/androidTest/java/org/moneymanagerex/android/testhelpers/UiTestHelpersRobotium.java
app/src/main/java/com/money/manager/ex/account/AccountEditActivity.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/investment/EditPriceDialog.java
app/src/main/java/com/money/manager/ex/investment/InvestmentTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/investment/PriceEditActivity.java
app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java
app/src/main/java/com/money/manager/ex/settings/PreferenceConstants.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

replace betterpickers with native DatePicker

---

app/build.gradle
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

explictly callOnClick for new transactionto generate TransNumber

---

docs/usermanual/asset-allocation.md
docs/usermanual/dropbox-concepts.md

Add note for remove asset management in documentation.
Close issue #1362 #1350 #1326 #1209 #900 #429

Update doc for asset

---

app/build.gradle
app/src/test/java/org/moneymanagerex/android/testhelpers/DataHelpers.java
app/src/test/java/org/moneymanagerex/android/tests/JavaMoneyTests.java
build.gradle

clean up gms

---

app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java

maybe Toast Message could be done better?

Fix #1359 Crash on open non mmb, Fix #1293 don't skip passcode

---

app/src/main/java/com/money/manager/ex/MmexApplication.java
app/src/main/java/com/money/manager/ex/settings/GeneralSettings.java
app/src/main/java/com/money/manager/ex/settings/GeneralSettingsFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_general.xml

main menu -> Settings -> General

support Opt users out of tracking

---

app/src/main/res/xml/preferences_sync.xml

hide upload immediately as still premature

---

app/build.gradle
app/src/main/java/com/money/manager/ex/MmexApplication.java
app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/settings/GeneralSettingsFragment.java
app/src/main/java/com/money/manager/ex/sync/SyncManager.java
app/src/main/java/com/money/manager/ex/sync/SyncService.java

reverse #1531

---

app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java

adjustment for search in subcategory (nested level)
fix #1532

adjustment for search in subcategory

---

app/src/main/java/com/money/manager/ex/reports/CategoriesReportFragment.java
app/src/main/java/com/money/manager/ex/reports/IncomeVsExpensesListFragment.java
app/src/main/java/com/money/manager/ex/reports/PayeeReportFragment.java
app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java

Fix total in report after going in detail view.

---

app/src/main/java/com/money/manager/ex/reports/IncomeVsExpensesListFragment.java

close issue #1546 by resolve regression test on #1540
sorry for mistakes :)

Fixed Crash in Report income/expense. 

---

docs/index.html

Update Documentation for FDroid

---

app/src/main/java/com/money/manager/ex/home/HomeFragment.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java

animations will automatically adapt to the user's preferences

---

app/src/main/java/com/money/manager/ex/datalayer/BudgetEntryRepository.java

protection code for category

---

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/java/com/money/manager/ex/transactions/SplitCategoriesActivity.java

allow zero amount transaction

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetPeriods.java
app/src/main/java/com/money/manager/ex/datalayer/BudgetEntryRepository.java

close issue #1566
Also fix Every 2 Months periods that didn't work.
Know issue: third level category still not present in budget. This will be fix with recursive budget

Compute correct budget with category

---

app/src/main/res/layout/item_splittransaction.xml
app/src/main/res/values/strings.xml

set better hint for insert a note

---

app/src/main/java/com/money/manager/ex/PasscodeActivity.java

Refine passcode input by request focus properly 

---

app/src/main/res/xml/preferences_behaviour.xml

SwitchPreferenceCompat => SwitchPreference

---

app/src/main/java/com/money/manager/ex/MmxContentProvider.java
app/src/main/java/com/money/manager/ex/datalayer/RepositoryBase.java
app/src/main/java/com/money/manager/ex/servicelayer/InfoService.java

fix update errors and pass proper conflictAlgorithm

---

app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

Make Payee as mandatory for non transfer tx

---

app/src/main/java/com/money/manager/ex/Constants.java
app/src/main/java/com/money/manager/ex/datalayer/AccountTransactionRepository.java
app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/utils/MmxDate.java

auto pop LASTUPDATEDTIME to comply with Desktop behavior

---

app/src/main/java/com/money/manager/ex/home/MainActivity.java

re-org reports

---

app/src/main/res/raw/query_alldata.sql
app/src/main/res/raw/query_mobiledata.sql

fix con rate to base

---

app/src/main/java/com/money/manager/ex/common/AllDataListFragment.java

fix #1632 and it was introduced since [v2024.03.16](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.03.16.1022)

fix transaction status update shortcut

---

app/src/main/java/com/money/manager/ex/common/CategoryListFragment.java
app/src/main/java/com/money/manager/ex/servicelayer/CategoryService.java
app/src/main/java/com/money/manager/ex/servicelayer/PayeeService.java

refactor update with args

---

app/src/main/java/com/money/manager/ex/common/CategoryListFragment.java

Fix subcategory edit/update bug

---

app/build.gradle
app/src/main/java/com/money/manager/ex/common/MmxBaseFragmentActivity.java
app/src/main/java/com/money/manager/ex/currency/CurrencyChartActivity.java
app/src/main/java/com/money/manager/ex/datalayer/AttachmentRepository.java
app/src/main/java/com/money/manager/ex/sync/SyncPreferenceFragment.java
app/src/main/java/com/money/manager/ex/transactions/AttachmentAdapter.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionViewHolder.java
app/src/main/res/layout/activity_edit_checking_account_transaction.xml
app/src/main/res/layout/item_attachment.xml

in its URI and a preview button 
permission is still TBD

Attachment display

---

app/src/main/java/com/money/manager/ex/common/CommonSplitCategoryLogic.java

transaction: support zero sum split transactions

---

app/build.gradle
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
fastlane/metadata/android/en-US/changelogs/1029.txt

2024.04.21.1029 crash for database file folder retrieval

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/home/DashboardFragment.java
app/src/main/java/com/money/manager/ex/reports/CategoriesReportFragment.java

ID as _id to comply with CursorAdapter

---

README.md
app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/notifications/RecurringTransactionNotifications.java
app/src/main/java/com/money/manager/ex/notifications/SyncNotificationModel.java
app/src/main/java/com/money/manager/ex/recurring/transactions/Recurrence.java
app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionEditActivity.java
app/src/main/res/layout/activity_edit_recurring_transaction.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml

I have add Schedule Transaction mode.
now in edit you can choise mode (Manual, Prompt, Auto) in according with Desktop version
Only Automatic transaction will be posted if posting is enable in setting
Close #1729

Handle Manual, Prompt & Automatic Transaction. See issue #1729

---

app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionEditActivity.java
app/src/main/res/layout/activity_edit_recurring_transaction.xml

Take care of DateFormat from setting in Payment Date

---

app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionListActivity.java
app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionListFragment.java

Recurring Notification improvement

---

app/src/main/java/com/money/manager/ex/view/behaviors/ScrollAwareFABBehavior.java

refine split transactions add/modify

---

app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/recurring/transactions/RecurringTransactionViewHolder.java
app/src/main/java/com/money/manager/ex/settings/BehaviourSettings.java
app/src/main/res/layout/activity_edit_recurring_transaction.xml

Code Clean (in Main and Recurring Transaction) & default to false for auto insert automatic trabsaction to prevent first time read from setting wrong & minor UI alignment for recurring transaction (close issue #1739)

Remove unused code & ui fix for Edit Recurring Transaction

---

app/src/main/java/com/money/manager/ex/MmxContentProvider.java

to fix the issue mentioned by #1770

refactor: clean up

---

app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/nestedcategory/QueryNestedCastegory.java
app/src/main/java/com/money/manager/ex/servicelayer/CategoryService.java
app/src/main/res/raw/query_onecategory.sql
doc/nestedcategory.md

Nestedcategory - parts 2

---

app/src/main/java/com/money/manager/ex/MmxContentProvider.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryEntity.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryTest.java
app/src/main/java/com/money/manager/ex/nestedcategory/QueryNestedCategory.java
app/src/main/java/com/money/manager/ex/servicelayer/CategoryService.java

@wolfsolver, can you take a look? this would be a follow up to #1760

Nest Category: fix arguments and class name typo

---

app/src/main/java/com/money/manager/ex/core/ContextMenuIds.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/nestedcategory/QueryNestedCategory.java
app/src/main/java/com/money/manager/ex/search/SearchParameters.java
app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java
app/src/main/res/values/strings.xml

Search Transaction including subtransaction from category list

NestedCategory Search Transaction with subcategory from category list

---

app/src/main/java/com/money/manager/ex/common/CalculatorActivity.java
app/src/main/java/com/money/manager/ex/common/CategoryListFragment.java
app/src/main/java/com/money/manager/ex/reports/BaseReportFragment.java

to fix #1786 
it was introduced by #1759 
detailed link: https://github.com/moneymanagerex/android-money-manager-ex/pull/1759/files#diff-a76be4ec88ed996319543401533c59286bfbc31e645ea7af64ebbebb5f944ec7

bugfix: add delete & equal button lambda back, due to #1759

---

app/src/main/java/com/money/manager/ex/database/ViewMobileData.java
app/src/main/java/com/money/manager/ex/reports/CategoriesReportFragment.java
app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java
app/src/main/res/layout/search_parameters_fragment.xml
app/src/main/res/values/strings.xml

Search with subcategory controlled by behavior switch and by user (subcategory search is not selectable is global switch for nested category is off)
update issue #1376

NestedCategory Search & Order

---

README.md

Update README.md JDK reference

---

app/src/main/java/com/money/manager/ex/reports/BaseReportFragment.java
app/src/main/res/menu/menu_period_picker.xml
app/src/main/res/values/strings.xml

Financial year in report

---

app/src/main/java/com/money/manager/ex/core/DefinedDateRangeName.java
app/src/main/java/com/money/manager/ex/core/DefinedDateRanges.java
app/src/main/java/com/money/manager/ex/utils/MmxDateTimeUtils.java
app/src/main/res/menu/menu_period_picker_transactions.xml

add Financial year in transaction list

---

app/src/main/res/raw/query_mobiledata.sql
app/src/main/res/raw/report_income_vs_expenses.sql

unify TRANSCODE handle logic during Amount and AmountBaseConvRate calc and use UNION ALL

unify TRANSCODE handle logic and use UNION ALL

---

app/build.gradle
app/src/main/java/com/money/manager/ex/settings/PerDatabaseFragment.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_per_database.xml

refine attachment preview by setting Attachment Folder

---

app/src/main/java/com/money/manager/ex/MmxContentProvider.java
app/src/main/java/com/money/manager/ex/common/AllDataListFragment.java
app/src/main/java/com/money/manager/ex/database/MmxOpenHelper.java
app/src/main/java/com/money/manager/ex/datalayer/SqlRepositoryBase.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/investment/EditPriceDialog.java
app/src/main/java/com/money/manager/ex/investment/PriceEditActivity.java
app/src/main/java/com/money/manager/ex/investment/watchlist/WatchlistFragment.java
app/src/main/java/com/money/manager/ex/settings/SyncPreferences.java
app/src/main/java/com/money/manager/ex/sync/SyncBroadcastReceiver.java
app/src/main/java/com/money/manager/ex/sync/SyncManager.java
app/src/main/java/com/money/manager/ex/sync/SyncPreferenceFragment.java
app/src/main/java/com/money/manager/ex/sync/SyncPreferencesViewHolder.java
app/src/main/java/com/money/manager/ex/sync/SyncSchedulerBroadcastReceiver.java
app/src/main/java/com/money/manager/ex/sync/SyncService.java
app/src/main/res/xml/preferences_sync.xml

1. always keep the sync enabled
2. always keep the sync service up

Synchronization enhancement

---

MMEX_Icon_Font/build.gradle
app/build.gradle
app/src/main/java/com/money/manager/ex/about/AboutFragment.java
app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java
app/src/main/java/com/money/manager/ex/utils/NotificationUtils.java
app/src/main/java/com/money/manager/ex/view/RobotoCheckBox.java
money/build.gradle

Upgrade minSdkVersion to 26, Android 8.0

---

app/src/main/res/values-ar/strings.xml
app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values-uk/strings.xml

major in Russian, Hindi, Arabic and Portuguese
thanks @pvphome

Update i18n on 2024-09-29 from Crowdin

---

app/build.gradle

Just a reminder:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.money.manager.ex.yml
```
gradle:
- fdroid
```

Refine product Flavor by distribution

---

app/src/main/java/com/money/manager/ex/sync/SyncManager.java
app/src/main/java/com/money/manager/ex/utils/NotificationUtils.java
app/src/main/res/values/strings.xml

This prevent crash and can allert user to reopen db.

Check if remote file is accessible. 

---

app/src/main/java/com/money/manager/ex/about/AboutFragment.java
app/src/main/res/layout/about_fragment.xml
docs/privacypolicy.md

Remove GooglePlus and update privacypolicy.md

---

app/src/main/java/com/money/manager/ex/common/CategoryListActivity.java

improve compatibility for new NestedCategory

Resolve dump notified by google play

---

app/src/main/java/com/money/manager/ex/sync/SyncManager.java
app/src/main/java/com/money/manager/ex/sync/SyncPreferenceFragment.java

Fix for remote file unavilable

---

app/src/main/AndroidManifest.xml

Google Play: remove legacy storage permission

---

app/src/main/java/com/money/manager/ex/search/CategorySub.java
app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java

close #1895
Switch from readInt to readLong in Parcel (complete SUID refinement)
Handle correct null in status filter

Restore Transaction search from category

---

app/src/main/java/com/money/manager/ex/common/AllDataListFragment.java

Fix bug of Integer2Long

---

app/src/main/java/com/money/manager/ex/common/CategoryListActivity.java
app/src/main/java/com/money/manager/ex/common/CategoryListFragment.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/transactions/SplitCategoriesActivity.java
app/src/main/java/com/money/manager/ex/transactions/events/CategoryRequestedEvent.java

Fix bug of Integer2Long for split transactions

---

app/src/main/java/com/money/manager/ex/payee/PayeeListFragment.java

Fix bug of Integer2Long for payee assign

---

app/src/main/java/com/money/manager/ex/servicelayer/CategoryService.java

Fix Check Category usage

---

app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java

honor -1 as invalid id

---

app/src/main/java/com/money/manager/ex/currency/CurrencyService.java
app/src/main/java/com/money/manager/ex/settings/DatabaseSettingsFragment.java
app/src/main/res/values/strings.xml

Fix for dump reported in gPlay

Stability: fix some dump reported by GPlay

---

app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java

 protect Toast in backgroup

---

app/src/main/java/com/money/manager/ex/about/AboutFragment.java
app/src/main/java/com/money/manager/ex/core/ioc/MmxComponent.java
app/src/main/java/com/money/manager/ex/home/DatabaseMetadata.java
app/src/main/res/layout/about_fragment.xml
app/src/main/res/values/strings.xml

Copy Version to clipboard & Directly Open Issue on Github

---

app/src/main/java/com/money/manager/ex/currency/list/CurrencyListFragment.java

Close #1930
and some clean code

Restore currency management in edit account (int2long)

---

app/src/main/java/com/money/manager/ex/reports/PayeeReportFragment.java

int2long in PayeeReportFragment

---

app/src/main/java/com/money/manager/ex/settings/BehaviourSettings.java
app/src/main/java/com/money/manager/ex/settings/BehaviourSettingsFragment.java
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

First step to remove old cat:subcat

Use always new nested category model

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java

Budget report must Honor fiscal year
Performance improvement

Budget financia year

---

app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java

Try to solve issue, but not sure that this is the solution
- #1969

Handling Recurring Transaction exception 

---

app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java

Handling Recurring Transaction exception

---

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

Copy Notes from Split if there is only one

---

app/src/main/java/com/money/manager/ex/database/ITransactionEntity.java
app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java
app/src/main/res/layout/activity_edit_recurring_transaction.xml

issue #735
add label in scheduled transaction

tag management (read mode)

---

app/src/main/java/com/money/manager/ex/database/ITransactionEntity.java
app/src/main/java/com/money/manager/ex/datalayer/TagRepository.java
app/src/main/java/com/money/manager/ex/datalayer/TaglinkRepository.java
app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/Tag.java
app/src/main/java/com/money/manager/ex/domainmodel/Taglink.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/notifications/RecurringTransactionProcess.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionListActivity.java
app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java
app/src/main/java/com/money/manager/ex/servicelayer/TagService.java
app/src/main/java/com/money/manager/ex/tag/TagActivity.java
app/src/main/java/com/money/manager/ex/tag/TagListFragment.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/java/com/money/manager/ex/viewmodels/AccountTransactionDisplay.java
app/src/main/res/layout/dialog_new_edit_tag.xml
app/src/main/res/menu-v14/menu_main.xml
app/src/main/res/menu/menu_main.xml
app/src/main/res/menu/menu_tag.xml
app/src/main/res/values/strings.xml

issue #735
There is still some feature to be implement

Tag management (edit mode & management)

---

app/src/main/java/com/money/manager/ex/MmxContentProvider.java
app/src/main/java/com/money/manager/ex/payee/PayeeListFragment.java

`CONFLICT_REPLACE` => `CONFLICT_IGNORE` and return -1 to indicate failure 
- #1988

CONFLICT_REPLACE to CONFLICT_IGNORE

---

build.gradle

continue of 
- https://github.com/moneymanagerex/android-money-manager-ex/pull/1843

Upgrade minSdkVersion to 28, Android 9.0

---

app/build.gradle
app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java
app/src/main/java/com/money/manager/ex/core/ioc/DbModule.java
app/src/main/java/com/money/manager/ex/database/MmxOpenHelper.java
app/src/main/java/com/money/manager/ex/sqlite3mc/SupportFactory.java
app/src/test/java/org/moneymanagerex/android/tests/MmexHelperTests.java
build.gradle

https://utelle.github.io/SQLite3MultipleCiphers/docs/configuration/config_sql_pragmas/#pragma-cipher

Encryption: switch to SQLite3MC

---

app/src/main/java/com/money/manager/ex/MmxContentProvider.java

SQLite3MC followup: fix parameter bindArgs

---

app/build.gradle
app/src/main/java/com/money/manager/ex/core/ioc/DbModule.java
app/src/main/java/com/money/manager/ex/database/MmxOpenHelper.java

SQLite3MC needs more test
- #1994

Encryption: switch to SQLite3MC revert

---

app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java

Crash: set default getRemoteFileModifiedDate

---

app/src/main/java/com/money/manager/ex/sync/SyncBroadcastReceiver.java
app/src/main/java/com/money/manager/ex/sync/SyncManager.java

ANR: just enable light check

---

app/src/main/res/layout/item_alldata_account.xml

to address part of 
- #2032 
- #1980

UEX: change Year text size back to micro from medium

---

app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java

Crash: return default value for edge case in getRemoteFileModifiedDate

---

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

manage clear all in tags

---

app/src/main/java/com/money/manager/ex/tag/TagListFragment.java
app/src/main/res/values/strings.xml

Honor PC constraint in tag

---

app/src/main/java/com/money/manager/ex/account/AccountTransactionListFragment.java
app/src/main/java/com/money/manager/ex/common/AllDataListFragment.java
app/src/main/java/com/money/manager/ex/database/QueryAllData.java
app/src/main/java/com/money/manager/ex/search/SearchActivity.java
app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java
app/src/main/res/raw/query_alldata.sql

Align report behaviours with MMEXDesktop. Show transaction at split level in report
Issue #2054

Align report behaviours with MMEXDesktop.

---

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

Ensure mTagLink is not null

---

app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionListFragment.java

Crash Fix: check null of getListAdapter

---

app/src/main/java/com/money/manager/ex/investment/InvestmentTransactionEditActivity.java

Crash Fix: check mAccount for onCommissionClick

---

app/src/main/java/com/money/manager/ex/core/Core.java

Refactor: add unicode support for highlight key words in search

---

build.gradle

Upgrade minSdkVersion to 29, Android 10

---

app/build.gradle
build.gradle

to fix #2068 
```
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: No virtual method transferTo(Ljava/io/OutputStream;)J in class Ljava/io/InputStream
```

Refactor: upgrade jvm target and source compatibility to Java 11

---

app/src/main/java/com/money/manager/ex/reports/BaseReportFragment.java

Correct Handling for Financial Year

---

docs/usermanual/backup-restore.md

Not sure where to put this, but it was originally in [this](https://github.com/moneymanagerex/android-money-manager-ex/issues/1827#issuecomment-2409879372) issue

add backup via Resilio Sync docs

---

.github/workflows/google_play_release.yml

I prepare new integration with gplay basewd on https://github.com/marketplace/actions/upload-android-release-to-play-store to publish in open test (beta).
I have some dubt regarding release file and position.
can be tested with next release

New integration with GPlay

---

app/src/main/java/com/money/manager/ex/adapter/AllDataAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetQuery.java
app/src/main/java/com/money/manager/ex/core/ExportToCsvFile.java
app/src/main/java/com/money/manager/ex/database/QueryAllData.java
app/src/main/java/com/money/manager/ex/database/QueryAllDataRepository.java
app/src/main/java/com/money/manager/ex/database/QueryMobileData.java
app/src/main/java/com/money/manager/ex/datalayer/BudgetEntryRepository.java
app/src/main/java/com/money/manager/ex/home/DashboardFragment.java
app/src/main/java/com/money/manager/ex/reports/BaseReportFragment.java
app/src/main/java/com/money/manager/ex/reports/CategoriesReportAdapter.java
app/src/main/java/com/money/manager/ex/reports/CategoriesReportFragment.java
app/src/main/java/com/money/manager/ex/utils/MmxDateTimeUtils.java
app/src/main/res/raw/query_alldata.sql
app/src/main/res/raw/query_budgets.sql
app/src/main/res/raw/query_mobiledata.sql

and fix issue discover for dirty transaction (set -1 if categoryid is null in DB)

Cleanup old code

---

app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
metadata/android/en-US/changelogs/1062.txt

2111 categories missing

---

app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java

Restore inactive category and add them to list in italic

Show both ACTIVE and INACTIVE categories

---

app/build.gradle
app/src/main/java/com/money/manager/ex/domainmodel/Category.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/res/raw/query_onecategory.sql
metadata/android/en-US/changelogs/1064.txt

Fix category active = null
Add category filter active in selection from transaction
Fix back pressed with no category selected and leave transaction category untouch

Fix category active = null and other minor issue

---

app/src/main/java/com/money/manager/ex/database/ISplitTransaction.java
app/src/main/java/com/money/manager/ex/datalayer/SplitCategoryRepository.java
app/src/main/java/com/money/manager/ex/datalayer/TaglinkRepository.java
app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/SplitCategory.java
app/src/main/java/com/money/manager/ex/domainmodel/SplitRecurringCategory.java
app/src/main/java/com/money/manager/ex/domainmodel/Taglink.java
app/src/main/java/com/money/manager/ex/notifications/RecurringTransactionProcess.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/java/com/money/manager/ex/transactions/SplitCategoriesAdapter.java
app/src/main/java/com/money/manager/ex/transactions/SplitItemViewHolder.java
app/src/main/java/com/money/manager/ex/utils/TagLinkUtils.java
app/src/main/res/layout/item_splittransaction.xml

issue discovered in copy for autopost. see #2142

Add tags in split transaction screen

---

app/build.gradle
app/src/main/java/com/money/manager/ex/adapter/AllDataAdapter.java
metadata/android/en-US/changelogs/1065.txt

2025.01.24 hotfix

---

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

Att Preview: try perform attachment folder sync for each transaction preview

---

app/src/main/java/com/money/manager/ex/adapter/AllDataAdapter.java
app/src/main/java/com/money/manager/ex/database/ITransactionEntity.java
app/src/main/java/com/money/manager/ex/datalayer/SplitCategoryRepository.java
app/src/main/java/com/money/manager/ex/datalayer/SplitScheduledCategoryRepository.java
app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java
app/src/main/java/com/money/manager/ex/notifications/RecurringTransactionProcess.java
app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java

Tag in Split - copy in autopost

---

app/src/main/java/com/money/manager/ex/home/MainActivity.java

to revert the changes from this PR
- #2050

Encryption: revert password input workflow

---

app/src/main/java/com/money/manager/ex/search/SearchParametersFragment.java

Set corect default for color

---

app/build.gradle
app/src/main/java/com/money/manager/ex/adapter/AllDataAdapter.java
app/src/main/java/com/money/manager/ex/common/AllDataListFragment.java
app/src/main/java/com/money/manager/ex/database/QueryMobileData.java
app/src/main/java/com/money/manager/ex/datalayer/TagRepository.java
app/src/main/java/com/money/manager/ex/domainmodel/Payee.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/payee/PayeeListFragment.java
app/src/main/java/com/money/manager/ex/reports/CategoriesReportAdapter.java
app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java
app/src/main/java/com/money/manager/ex/servicelayer/TagService.java
app/src/main/java/com/money/manager/ex/settings/AppSettings.java
app/src/main/java/com/money/manager/ex/tag/TagListFragment.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java
app/src/main/res/menu/menu_sort.xml
app/src/main/res/raw/query_alldata.sql
app/src/main/res/raw/query_mobiledata.sql
app/src/main/res/values/strings.xml
metadata/android/en-US/changelogs/1067.txt

V1067 for release

---

app/src/main/java/com/money/manager/ex/payee/PayeeListFragment.java

Fix Viewing transaction make inactive payee. Partial Fix #2217
Fix backward compatibility for payee.active = null. Close #2216

Payee but fix

---

app/src/main/java/com/money/manager/ex/account/AccountListFragment.java

Force refresh in account list after creation

---

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java

Forgot to comment the line 
msgSender = "AT-SIBSMS";

Minor correction in the SMS Receiver

---

app/src/main/java/com/money/manager/ex/datalayer/RepositoryBase.java

Database Sync: re-enable SUID

---

app/src/main/java/com/money/manager/ex/currency/CurrencyEditActivity.java
app/src/main/java/com/money/manager/ex/currency/CurrencyRepository.java
app/src/main/java/com/money/manager/ex/currency/CurrencyService.java
app/src/main/java/com/money/manager/ex/database/QueryAllDataRepository.java
app/src/main/java/com/money/manager/ex/datalayer/AccountRepository.java
app/src/main/java/com/money/manager/ex/datalayer/AccountTransactionRepository.java
app/src/main/java/com/money/manager/ex/datalayer/AttachmentRepository.java
app/src/main/java/com/money/manager/ex/datalayer/BudgetRepository.java
app/src/main/java/com/money/manager/ex/datalayer/RepositoryBase.java
app/src/main/java/com/money/manager/ex/datalayer/ScheduledTransactionRepository.java
app/src/main/java/com/money/manager/ex/datalayer/SplitCategoryRepository.java
app/src/main/java/com/money/manager/ex/datalayer/SplitScheduledCategoryRepository.java
app/src/main/java/com/money/manager/ex/datalayer/StockHistoryRepository.java
app/src/main/java/com/money/manager/ex/datalayer/StockRepository.java
app/src/main/java/com/money/manager/ex/datalayer/TagRepository.java
app/src/main/java/com/money/manager/ex/datalayer/TaglinkRepository.java
app/src/main/java/com/money/manager/ex/domainmodel/StockHistory.java
app/src/main/java/com/money/manager/ex/investment/InvestmentTransactionEditActivity.java

Database Sync: centralize entity create/add

---

app/src/main/java/com/money/manager/ex/home/MainActivity.java

Using openHelper for reading database in General Report

Using openHelper for reading database in General Report

---

app/src/main/java/com/money/manager/ex/common/AllDataListFragment.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/payee/PayeeListFragment.java
app/src/main/java/com/money/manager/ex/settings/AppSettings.java
app/src/main/java/com/money/manager/ex/tag/TagListFragment.java
app/src/main/res/menu/menu_sort.xml
app/src/main/res/menu/menu_sort_transaction.xml
app/src/main/res/values/strings.xml

close #2208
Also add sort in transaction list result

add Menu Item for Filter Inactive Tag, Category and Payee

---

app/src/main/java/com/money/manager/ex/datalayer/ReportRepository.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/reports/GeneralReportActivity.java
app/src/main/java/com/money/manager/ex/reports/GeneralReportFragment.java
app/src/main/res/values/strings.xml

Corrected following issues reported by @wolfsolver ,
- back arrow does not work from inside report
- in my version menu as empty string, so maybe missing label

Handled Report having blank group name

---

app/src/main/java/com/money/manager/ex/datalayer/AccountTransactionRepository.java
app/src/main/java/com/money/manager/ex/datalayer/AttachmentRepository.java
app/src/main/java/com/money/manager/ex/datalayer/PayeeRepository.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java

1. AttachmentRepository provides basic `loadByRef(long refId, RefType refType) `
2. AccountTransactionRepository has interface `loadAttachments(long id)`

ORM: normalize attachments retrieve by trx

---

app/src/main/java/com/money/manager/ex/database/MmxOpenHelper.java
app/src/main/res/raw/database_version_20.sql

Since Desktop 1.9.0 is now available for all, it's time to upgrade also mobile

Update to DB 20

---

app/src/main/java/com/money/manager/ex/datalayer/ReportRepository.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/reports/GeneralReportFragment.java

Added Report under drawer menu when there is no group

Added Report under drawer menu when there is no group

---

app/src/main/java/com/money/manager/ex/datalayer/StockRepository.java

close #2295
anr-1071-stockrepository

fix null in stock repo

---

app/src/main/java/com/money/manager/ex/core/AbsListFragment.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryEntity.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/nestedcategory/QueryNestedCategory.java
app/src/main/java/com/money/manager/ex/settings/AppSettings.java
app/src/main/res/layout/simple_list_item_1_with_selector.xml
app/src/main/res/raw/query_onecategory.sql

First Review for nested category
feedback welcome

new nestedCategory management

---

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

after refactor from float button in main screen (with default account) dump.

Dump fix while enter transaction from float button

---

app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml

Added Support for the language "Tamil". @wolfsolver , thankyou so much. It worked after adding the entry.

Added Support for language "Tamil"

---

app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java
app/src/main/java/com/money/manager/ex/reports/CashFlowReportListFragment.java
app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java

close #2234 
- add correct handling for transfert
- add multicurrency support
- add account if payee not present

2234 new cash flow report

---

app/src/main/java/com/money/manager/ex/budget/BudgetEditActivity.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/sync/SyncPreferenceFragment.java
app/src/main/res/values/strings.xml

Add language translation for DB Download & Upload Warning Dialog
- #2303

Add more language translations 

---

app/src/main/java/com/money/manager/ex/MmxContentProvider.java
app/src/main/java/com/money/manager/ex/datalayer/ReportRepository.java
app/src/main/java/com/money/manager/ex/reports/GeneralReportFragment.java

1. re-use `MmxContentProvider` and `SQLDataSet`

ORM: support run rawQuery, use it in GRM and use StringBuilder over String

---

app/src/main/java/com/money/manager/ex/sync/SyncPreferenceFragment.java

Minor Correction in Download Warning Msg

Minor Correction in Download Warning Msg

---

app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/passcode/PasscodeActivity.java
app/src/main/java/com/money/manager/ex/settings/PreferenceConstants.java
app/src/main/java/com/money/manager/ex/settings/SecuritySettings.java
app/src/main/java/com/money/manager/ex/settings/SecuritySettingsFragment.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences_security.xml

1. Hidden Biometric UI when the user activates or edits the passcode. This will appear only during app startup and disabling the passcode
2. Added option under security to enable Fingerprint

Added option under security to enable Fingerprint Authentication

---

metadata/android/en-US/changelogs/1072.txt

Update to release notes 1072.txt

---

metadata/android/en-US/changelogs/1072.txt

Removed "Reports: Fixed issues where reports had blank group names and added more detailed report results. "

Update 1072.txt with Enhancements

---

app/src/main/java/com/money/manager/ex/datalayer/TaglinkRepository.java
app/src/main/java/com/money/manager/ex/utils/TagLinkUtils.java

fix #2328 as these are creation instead of update

Tag: fix tag save/re-creation bug

---

app/src/main/java/com/money/manager/ex/servicelayer/RecurringTransactionService.java

Honor number of payement in CashFlow Report

---

app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java

instead of LoaderManage.getInstance
close #2332

Restore getLoaderManager

---

app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java

fix regression on https://github.com/moneymanagerex/android-money-manager-ex/commit/e13cceebe60ae4b0674b4e513ff71669b8435b4f

fix issue on transaction is empy

---

app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java

fix issue on transaction is empty

5.1.2 : fix-getTransactionNumber

---

app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionListActivity.java

5.1.2 Branch: Show Fingerprint Authentication if it is launched from the Notification

5.1.2 Branch: Show Fingerprint Authentication if it is launched from the Notification

---

app/src/main/java/com/money/manager/ex/datalayer/TagRepository.java
app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/reports/cashflow/CashFlowReportListFragment.java

search in all subcategory of current selected category
close #2370
Cashflow report enhanced #2357

Search in subcategory even if navigation tree is on & CashFlow Graph Refinement

---

app/build.gradle

@guanlisheng can you have a look?
Some change on gradle:
1) for DEBUG: add new version name based on branch for easy understand when running on android whic version is running by 
`versionNameSuffix "-debug-" + getCurrentBranch() + "-" + getVersionAsDate()`
2) for Release add data as request by google https://developer.android.com/build/shrink-code
```
minifyEnabled true
shrinkResources true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```
but not sure that is anough

New Gradle refinement for gplay and test

---

app/build.gradle
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionListFragment.java
metadata/android/en-US/changelogs/1076.txt

I made previus error becouse push to master instead of 5.1

5.1.4 patch su Release 5.1

---

app/src/main/java/com/money/manager/ex/reports/cashflow/CashFlowReportListFragment.java

- added select point in graph move list at day position
- add filter for open account in selector if setting has use only open

Cashflow - add features

---

app/src/main/java/com/money/manager/ex/reports/cashflow/CashFlowReportListFragment.java

https://github.com/moneymanagerex/android-money-manager-ex/pull/2402#issuecomment-2708171033

CashFlow refinement - improve menu handling

---

app/build.gradle

Remove ProGuard from gradle

---

app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java

Preserve master note if split has empty note

---

app/src/main/java/com/money/manager/ex/nestedcategory/NestedCategoryListFragment.java
app/src/main/java/com/money/manager/ex/reports/cashflow/CashFlowReportListFragment.java

Final Cashflow developement

---

app/src/main/java/com/money/manager/ex/datalayer/StockRepository.java

1. leverage `RepositoryBase.query` and remove  duplicated `getEntities`
2. add `loadByAccount`

ORM: StockRepository refine and simplify

---

app/src/main/java/com/money/manager/ex/domainmodel/Attachment.java

Parcellable Attachment

---

app/src/main/java/com/money/manager/ex/reports/cashflow/CashFlowReportListFragment.java

set color from theme.

---

app/src/main/java/com/money/manager/ex/reports/GeneralReportFragment.java

if any of the column name contains amount, deposit, withdrawal, total and initialbal, then these column values will be formated with currency

General Report: Added currency format and red color for negative value

---

app/src/main/java/com/money/manager/ex/MmexApplication.java

Locale from language fix

---

app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java

@guanlisheng  can you give a feedback. I think that need a deeper check or more extend approach

2441-transdate-has-mixed-format-with-or-without-t000000

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java
app/src/main/java/com/money/manager/ex/budget/BudgetPeriodEnum.java
app/src/main/res/layout/item_budget_simple.xml
app/src/main/res/layout/item_budget_simple_header.xml
app/src/main/res/menu/menu_budget.xml
app/src/main/res/values/strings.xml

close #2431 caused by #2317
still open to create xml custom layout to enter budget period

handle default in budget entry

---

app/src/main/java/com/money/manager/ex/settings/DatabaseSettingsFragment.java

Additional changes for Setting fragment setting title

Additional changes for Setting database fragment setting title #2347

---

app/src/main/java/com/money/manager/ex/investment/PortfolioListAdapter.java
app/src/main/res/layout/item_portfolio.xml

Stock: refine portfolio with two lines in one column

---

app/src/main/java/com/money/manager/ex/settings/InvestmentSettings.java

fix dump in provider setting

---

app/src/main/java/com/money/manager/ex/servicelayer/AccountService.java

Excluded Deleted Transaction from balance.

---

app/build.gradle
metadata/android/en-US/changelogs/1078.txt

* fix dump in provider setting
* Fix dump in category search
* Add app version in crash
* Excluded Deleted Transaction from balance
* Correct language translation for report

Preparing release 5.2.1

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java
app/src/main/java/com/money/manager/ex/budget/BudgetPeriodEnum.java
app/src/main/java/com/money/manager/ex/budget/BudgetPeriods.java
app/src/main/java/com/money/manager/ex/domainmodel/Budget.java

*  Fix compute in montly budget (considering also year in select)
* New Estimate. so estimate is equal to Desktop Version

initial refinement for budget

---

app/src/main/res/values/currencies.xml

Fix error while manually update currency exchange rate

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java
app/src/main/java/com/money/manager/ex/settings/AppSettings.java
app/src/main/java/com/money/manager/ex/settings/BudgetSettings.java
app/src/main/res/layout/item_budget.xml
app/src/main/res/layout/item_budget_header.xml
app/src/main/res/menu/menu_budget.xml
app/src/main/res/values/strings.xml

* Layout refinement
* Selectable Columns via menu
* Code refactor

2458 budget feature

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java
app/src/main/res/menu/menu_budget.xml

Add cumulative total is flag useSubCategory is set

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java
app/src/main/res/layout/activity_budget_edit.xml
app/src/main/res/values/strings.xml

* handle correct special char like " and '. Close #2492
* Ignore Inactive category in budget. Close #2493
* [Budget fix - show optional for month and income](https://github.com/moneymanagerex/android-money-manager-ex/pull/2495/commits/07bd579e2436eab7aa592b49fdc4a6ef62548a37) https://github.com/moneymanagerex/android-money-manager-ex/issues/2494

Budget fix

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java
app/src/main/res/layout/item_budget.xml
app/src/main/res/layout/item_budget_header.xml
app/src/main/res/menu/menu_budget.xml
app/src/main/res/values/strings.xml

Rename columns becouse Estimate Value is not alsways yearly, but if budget is monttly is montly :)

Rename Column for Period Estimate

---

docs/index.html

Fix GPL logo & github forkicon

---

app/src/main/java/com/money/manager/ex/core/ContextMenuIds.java
app/src/main/java/com/money/manager/ex/home/HomeFragment.java

Stock: set portfolio as default of click

---

app/src/main/java/com/money/manager/ex/domainmodel/Stock.java
app/src/main/java/com/money/manager/ex/investment/PortfolioFragment.java
app/src/main/res/layout/fragment_portfolio.xml

1. ActivityResultLauncher + registerForActivityResul to replace startActivityForResult
2. more field for hashcode and equals

Stock: refine portfolio impl

---

app/src/main/java/com/money/manager/ex/reports/CategoriesReportFragment.java
app/src/main/java/com/money/manager/ex/reports/PayeeReportFragment.java

disable fab in category report

---

app/src/main/java/com/money/manager/ex/budget/BudgetEditViewHolder.java

fix occasionally dump in budget

---

app/build.gradle
app/src/main/java/com/money/manager/ex/servicelayer/InfoService.java
metadata/android/en-US/changelogs/1081.txt

close #2528 
Probability due dirty color record

Hotfix for color > 7

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduleTransactionForecastList.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionForecastListServices.java

Performance improvement on Budget Forecast

---

app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/tutorial/TutorialActivity.java

Ask notification permission

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java
app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java
app/src/main/java/com/money/manager/ex/database/ITransactionEntity.java
app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/domainmodel/RecurringTransaction.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduleTransactionForecastList.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/scheduled/ScheduledTransactionForecastListServices.java
app/src/main/res/menu/menu_budget.xml
app/src/main/res/values/strings.xml

New Budget Feature

---

app/src/main/java/com/money/manager/ex/settings/SettingsActivity.java
app/src/main/java/com/money/manager/ex/sync/SyncManager.java
app/src/main/res/values/strings.xml

close #2056
Restore cansync with check for availability of remote file. This is necessary becouse some SAF loose connection after a while (like OneDrive) on some Andorid version (like 12).
This give user ability to:
- go to setting for manual backup 
- go directly to open from remote

support user to handle sync error

---

app/src/main/java/com/money/manager/ex/budget/BudgetAdapter.java

Fix Budget coreDump by missing context

---

app/src/main/java/com/money/manager/ex/datalayer/AssetRepository.java
app/src/main/java/com/money/manager/ex/datalayer/CurrencyHistoryRepository.java
app/src/main/java/com/money/manager/ex/datalayer/CustomFieldDataRepository.java
app/src/main/java/com/money/manager/ex/datalayer/CustomFieldRepository.java
app/src/main/java/com/money/manager/ex/datalayer/TransactionLinkRepository.java
app/src/main/java/com/money/manager/ex/domainmodel/Asset.java
app/src/main/java/com/money/manager/ex/domainmodel/CurrencyHistory.java
app/src/main/java/com/money/manager/ex/domainmodel/CustomField.java
app/src/main/java/com/money/manager/ex/domainmodel/CustomFieldData.java

to fix the issues mentioned in 
- #2260

ORM: complete missing domain model and repository

---

app/src/main/java/com/money/manager/ex/budget/BudgetEditViewHolder.java

Prevent null model. 

---

app/src/main/java/com/money/manager/ex/budget/BudgetEditViewHolder.java

Fix wrong check on budgetYearTextView

---

app/src/main/java/com/money/manager/ex/core/docstorage/FileStorageHelper.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/home/SelectDatabaseActivity.java

Fix Error while create existing db

---

app/src/main/java/com/money/manager/ex/investment/PortfolioListAdapter.java

Fix dump on PortfolioListAdapter

---

app/build.gradle
app/src/main/java/com/money/manager/ex/investment/PortfolioListAdapter.java
app/src/main/java/com/money/manager/ex/sync/SyncManager.java
metadata/android/en-US/changelogs/1084.txt

Fix Portfolio also on this branch
Fix timeout from gPlay

Release 5.3.x

---

app/src/main/java/com/money/manager/ex/notifications/SmsReceiverTransactions.java

Changed parseInt to Long.parseLong for accountid & txnid

Changed parseInt to Long.parseLong for accountid & txnid

---

app/src/main/java/com/money/manager/ex/budget/BudgetEntryFragment.java
app/src/main/res/layout/budget_edit_entry.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values-hu-rHU/strings.xml
app/src/main/res/values-it-rIT/strings.xml
app/src/main/res/values-ru-rRU/strings.xml
app/src/main/res/values-ta-rIN/strings.xml
app/src/main/res/values/strings.xml

Budget: new edit budget entry with amount and frequency.

---

app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/investment/PortfolioListAdapter.java

hide General Report if it is empty

---

app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java

Added Long.parseLong in place of ParseInt. Also added condition only for account id and removed for the amount

Added Long.parseLong in place of ParseInt

---

.github/workflows/jekyll-gh-pages.yml

Main scope is to prevent site generation if docs/* has no changes

Create jekyll-gh-pages.yml to switch from page ambeded to github action 

---

README.md
app/build.gradle
app/src/main/java/com/money/manager/ex/MmexApplication.java
app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
build.gradle
gradle/wrapper/gradle-wrapper.properties
metadata/android/en-US/changelogs/1089.txt

Almost done, expect for issue #2672

Plugins upgrade

---

app/build.gradle
app/src/main/java/com/money/manager/ex/MmexApplication.java
app/src/main/java/com/money/manager/ex/database/MmxOpenHelper.java
build.gradle
gradle/wrapper/gradle-wrapper.properties
metadata/android/en-US/changelogs/1089.txt
metadata/android/en-US/changelogs/1090.txt

sqlcipher upgrade for Android 15
close #2672

Sqlcipher android

---

app/build.gradle
app/src/main/java/com/money/manager/ex/about/WhatNewManager.java
app/src/main/java/com/money/manager/ex/common/MmxBaseFragmentActivity.java
app/src/main/java/com/money/manager/ex/transactions/CheckingTransactionEditActivity.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionViewHolder.java
app/src/main/res/layout/activity_edit_checking_account_transaction.xml
app/src/main/res/layout/activity_edit_recurring_transaction.xml
app/src/main/res/layout/main_activity.xml
metadata/android/en-US/changelogs/1092.txt

Set Drawers for edge-to-edge
close #2677

Android 15 compatibility & release 5.4.5

---

README.md
app/build.gradle
app/src/main/java/com/money/manager/ex/MmexApplication.java
app/src/main/java/com/money/manager/ex/common/MmxBaseFragmentActivity.java
app/src/main/java/com/money/manager/ex/domainmodel/AccountTransaction.java
app/src/main/java/com/money/manager/ex/home/MainActivity.java
app/src/main/java/com/money/manager/ex/home/MyActionBarDrawerToggle.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionCommonFunctions.java
app/src/main/java/com/money/manager/ex/transactions/EditTransactionViewHolder.java
app/src/main/java/com/money/manager/ex/tutorial/TutorialActivity.java
app/src/main/res/layout/activity_edit_checking_account_transaction.xml
app/src/main/res/layout/activity_edit_recurring_transaction.xml
app/src/main/res/layout/activity_tutorial.xml
app/src/main/res/layout/main_activity.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/theme_dark.xml
app/src/main/res/values/theme_light.xml
app/src/main/res/values/themes.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
metadata/android/en-US/changelogs/1093.txt

Due heavy change to android 15, rollback to android 14.

Rollback to Android 14 - Release 5.4.6

---

app/src/main/res/values/themes.xml
build.gradle

to fix 
- #2677
https://developer.android.com/build/releases/gradle-plugin#api-level-support

Android 15: upgrade SDK to 35, AGP to 8.6.1 and opt out edge-to-edge
